### ISSUE TITLE
115下载到服务器再上传产生临时文件

### ISSUE THREAD

**Issue by StefanZhang** [nudgee28/gdtransfer#1]
你好,
使用115客户端下载的时候会产生临时文件,这个中间文件不也会被软件上传到谷歌盘吗?
还有就是怎么设定上传以后自动删除文件呢? 要不然大文件就得删一个再下载新的了,挺麻烦的.

**Comment by nudgee28** [comment]
下载目标盘直接选GD的盘，不要先下本地盘，这样直接缓存过去不会产生大量的文件。
